title: Mason Nakamura
logo: /assets/img/MasonPhoto.JPG
description: Personal Website
show_downloads: false
google_analytics: G-HK6QKBXJ34
remote_theme: gebeto/researcher

# footer: "Page design by Ankit Sultana"
# footer_url: "https://github.com/ankitsultana"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
